### ISSUE TITLE
Errors with make

### ISSUE THREAD

**Issue by zirion** [libnifalcon/libnifalcon#25]
[ 44%] Building CXX object src/util/CMakeFiles/nifalcon_cli_base_SHARED.dir/FalconCLIBase.cpp.o
Linking CXX shared library ../../lib/libnifalcon_cli_base.so

/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/4.7.0/../../../../lib/libboost_program_options.a(cmdline.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC

/usr/lib/gcc/x86_64-unknown-linux-gnu/4.7.0/../../../../lib/libboost_program_options.a: could not read symbols: Bad value
collect2: error: ld returned 1 exit status

make[2]: *** [lib/libnifalcon_cli_base.so.1.0.0] Error 1
make[1]: *** [src/util/CMakeFiles/nifalcon_cli_base_SHARED.dir/all] Error 2
make: *** [all] Error 2

**Comment by MAGPC** [comment]
I am still having the same issue, any solutions found?

**Comment by FabienDanieau** [comment]
There is no dependency to boost anymore. This issue should be fixed.
