### ISSUE TITLE
Linux (Debian Jessie w/ Kernel 3.14.2) no longer needs powered usb hub?

### ISSUE THREAD

**Issue by qdot** [libnifalcon/libnifalcon#33]
Just got support email from someone who was having problems running libnifalcon on linux. Firmware loading was extremely flakey. Tried it myself, and sure enough, the instructions in the readme to always use a powered USB hub no longer seem to work. I had to plug the falcon directly into a usb port on my thinkpad to get firmware to load. Once firmware was loaded, things seemed to work fine.

Not sure what changed or when to cause this, but it might be worth updating README to reflect the issue.

**Comment by FabienDanieau** [comment]
A usb powered hub is not necessary indeed.

Regarding the loading of the firmware, yes it does not load at first. You often need to do it several times.
