### ISSUE TITLE
I can't use from python

### ISSUE THREAD

**Issue by sjtosco** [libnifalcon/libnifalcon#36]
After install and change OFF to ON in CMakeLists.txt the corresponding lines:

OPTION(STATIC_LINK_SUFFIXES "Add a symbolic link with [library_name]_s on static libraries (for ease in building staticly linked binaries under gcc)" ON)
OPTION(BUILD_SWIG_BINDINGS "Build Java/Python bindings for libnifalcon" ON)
OPTION(BUILD_EXAMPLES "Build libnifalcon examples" ON)

I try .py examples from build folder and this not function... Not found pynifalcon module.
I think that is like a path problem... Can anybody helpme? Thanks!

**Comment by qdot** [comment]
Just saw your email (wow I am bad at email). Hmm. I haven't built the python stuff in like, 7 years, so who knows if it even still works. :( Will try to take a look at this sometime soon.

**Comment by sjtosco** [comment]
Thanks, my friend! I will appreciate any clue that you could give me!
Regards!

--
SJTosco


Sent from my ASUS

-------- Mensaje original --------
De:Kyle Machulis <notifications@github.com>
Enviado:Mon, 02 May 2016 21:23:11 -0300
Para:libnifalcon/libnifalcon <libnifalcon@noreply.github.com>
Cc:sjtosco <sjtosco@yahoo.com.ar>,Author <author@noreply.github.com>
Asunto:Re: [libnifalcon/libnifalcon] I can't use from python (#36)

**Comment by FabienDanieau** [comment]
Hi,

I just compiled the library and python bindings.
If it succeeds, you may have pynifalcon.py in <build-folder>/lang/swig/ and _pynifalcon.so in <build_folder>/lib/  

Now you can run the examples from the source (libnifalcon/lang/examples/python/pynifalcon_led_test.py for instance). If you have an error like "ImportError: No module named pynifalcon", it is because your PYTHONPATH is not set. Python needs to know where pynifalcon.py and 
_pynifalcon.so.

To fix that you need to set the global variable PYTHONPATH. For instance with Linux:
export PYTHONPATH=$PYTHONPATH:<build_folder>/lang/swig:<build_folder>/lib

Hope it helps. Let me know if you have others questions.

**Comment by sjtosco** [comment]
Thanks!!!

I'll test this...

Best Regards


On 05/05/16 11:55, Fabien wrote:
>
> Hi,
>
> I just compiled the library and python bindings.
> If it succeeds, you may have pynifalcon.py in /lang/swig/ and 
> _pynifalcon.so in /lib/
>
> Now you can run the examples from the source 
> (libnifalcon/lang/examples/python/pynifalcon_led_test.py for 
> instance). If you have an error like "ImportError: No module named 
> pynifalcon", it is because your PYTHONPATH is not set. Python needs to 
> know where pynifalcon.py and
> _pynifalcon.so.
>
> To fix that you need to set the global variable PYTHONPATH. For 
> instance with Linux:
> export PYTHONPATH=$PYTHONPATH:/lang/swig:/lib
>
> Hope it helps. Let me know if you have others questions.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/libnifalcon/libnifalcon/issues/36#issuecomment-217175861>
>

-- 
SJTosco

**Comment by FabienDanieau** [comment]
Can we close this issue?

**Comment by sjtosco** [comment]
Hi! Sorry. i close this Ticket right now. Thank for your help! Regards!

**Comment by sjtosco** [comment]
Hi! Sorry. i close this Ticket right now. Thank for your help! Regards!


On 04/07/16 18:42, Fabien wrote:
>
> Can we close this issue?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/libnifalcon/libnifalcon/issues/36#issuecomment-230357012>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AFMeOTO23ObIlB3MlkProhjRudz5e21Lks5qSX5FgaJpZM4H3Q0e>.
>

-- 
SJTosco
