### ISSUE TITLE
Should I make libnifalcon an organization repo? We need more maintainers

### ISSUE THREAD

**Issue by qdot** [libnifalcon/libnifalcon#37]
I did not realize I wasn't getting notifications for libnifalcon issues, which means we've had nice fixes in pull requests sitting around, sometimes for years. If I move this to be an organization repo, would others be interested in helping out with maintenance? Please reply here if interested and I'll try to keep up.

**Comment by FabienDanieau** [comment]
I cannot spend a lot of time on this, but I would be happy to help. I mostly work with Linux (Debian)

**Comment by AlexJaeger** [comment]
I'd be happy to help. I'll mostly be working with Windows

**Comment by qdot** [comment]
Ok, I'll try to get this split off into an organization and get both of you added then. No sense holding it on my personal account.

**Comment by qdot** [comment]
Ok, all done! Both of you have invites to the new org, with r/w rights to the libnifalcon repo. Moving all my falcon repos over to the org now I'll fork them back to my own account as this project has 9 years of history, so lots of links I'd rather not see go away).
