### ISSUE TITLE
Falcon not found [Windows 10]

### ISSUE THREAD

**Issue by mattandria** [libnifalcon/libnifalcon#51]
Hello there,

I'm trying to make the Falcon work with libnifalcon on Windows 10. 
Like the README advised to do, I installed Boost (version 1.69) and FtD2xx. 
The compilation on Cmake and the generation of the solution for Visual Studio worked, and building the solution as well. 
I plug the Falcon and when I launch the `findfalcon.exe`, I get this on the console:

> Falcons found: -1
Opening falcon 1
Cannot open falcon - Error:

Is there another thing I have to do before running the executable?

Thank s in advance!

**Comment by mattandria** [comment]
Ok,I finally found what's wrong. Actually, it was a matter of driver: I did'nt use the right one. Instead of using FtDxx, I used Force Dimension. So I just removed it and reinstalled Ftd2xx. And now it works !!!!

**Comment by qdot** [comment]
Ah, well, glad to know this still works. :)
